### ISSUE TITLE
Challenges

### ISSUE THREAD

**Issue by Crapulax** [janekolszak/idp#28]
Hello,

First of all, thanks for providing this library!

Would you be able to point me in the right direction? I do not ask you to solve my issue but just let me know what I should look into...

I am using the form with rethinkdb and get it working within my environment. But I never get the consent request. 
- I register my user, ok
- got verification email ok
But then when i moved back to /, I do not get redirected to /consent.

From the code I can see that this is because there is no challenge in the request.
                challenge, err := h.IDP.NewChallenge(r, user)
		if err != nil { <=== err not nil.... Bad request
			fmt.Println(err.Error())
			h.Provider.WriteError(w, r, err)
			return
		}

My question is how am I supposed to get it? I am missing something probably silly as I am new to IDP.
Can you give me a hint or a few words about the expected worklflow?

Thanks a lot,
Steve.

**Comment by janekolszak** [comment]
Hi there!

The example with Form provider and RethinkDB isn't finised. 

Challenge comes from Hydra via query param and gets stored in a short lived cookie for the login and consent screens.  The _/register_ endpoint should create a Challenge just like _/_. Nobody had the time to implement this :/

PR's are welcomed of course. 

If you need any other help we use https://gitter.im/janekolszak/idp for discussion.
If you choose to implement this let us know on gitter.

**Comment by Crapulax** [comment]
Dziękuję!!

I was starting to become crazy:)
I need to implement an authorization code flow and use your stuff as a starting point. I also have my own DB. If you believe that this makes sense in your context I might implement it on top instead of breaking everything:).

All the best,
Steve.


Sent from my iPhone

On 7 août 2016, at 21:21, Jan Olszak <notifications@github.com> wrote:

Hi there!

The example with Form provider and RethinkDB isn't finised.

Challenge comes from Hydra via query param and gets stored in a short lived cookie for the login and consent screens. The /register endpoint should create a Challenge just like /. Nobody had the time to implement this :/

PR's are welcomed of course.

If you need any other help we use https://gitter.im/janekolszak/idp for discussion.
If you choose to implement this let us know on gitter.

**Comment by janekolszak** [comment]
No problem,
If you choose to implement a Provider and a UserStore you can use the provided interfaces, but they are likely to change this month.

All contributions are welcomed. 
What database do you use?

**Comment by Crapulax** [comment]
I am using Couchbase

 

De : Jan Olszak [mailto:notifications@github.com] 
Envoyé : lundi 8 août 2016 11:17
À : janekolszak/idp <idp@noreply.github.com>
Cc : Crapulax <steve.faye@free.fr>; Author <author@noreply.github.com>
Objet : Re: [janekolszak/idp] Challenges (#28)

 

No problem,
If you choose to implement a Provider and a UserStore you can use the provided interfaces, but they are likely to change this month.

All contributions are welcomed. 
What database do you use?

**Comment by janekolszak** [comment]
Good luck! 

If your're going to implement a simple example with CouchDB as a startup please contribute.:)
