### ISSUE TITLE
Using a better name for Respond in Provider interface

### ISSUE THREAD

**Issue by faxal** [janekolszak/idp#3]
Wouldn't it be better for `Provider` to have something similar to `WriteError` instead of `Respond`. I feel that `Respond` means to send a normal response of some sort.

I wanted to quickly highlight this before API matures, while we still have a chance to break the API.

Appreciate what you've done here. It's a huge undertaking. :+1:

**Comment by janekolszak** [comment]
Agreed

**Comment by faxal** [comment]
Assuming `WriteError` is okay, I'll send PR in a bit

**Comment by janekolszak** [comment]
It's not always an error. `Respond` is supposed to give user a way of authenticating. Sometimes it's written on an error, but sometimes not. 

When using a http form it will have to write the whole html login page, with digestauth it will add some headers to the response.

For example GET on /login endpoint will automatically do `Respond` to give the user a login form to fill. WriteError would write something like "Dear user, your credentials are bad, try again" and write the same form.

**So I think we need both - Write and WriteError. In BasicAuth they will do the same thing, but in `FormProvider` they won't.**

**Comment by faxal** [comment]
:+1: I just read the interface description and assumed it was only for errors.
