### ISSUE TITLE
using go-cache prevents HA deployment

### ISSUE THREAD

**Issue by boyvinall** [janekolszak/idp#4]
It would be good if a high-availability configuration was possible. Using go-cache prevents this as it's all in single-process on one machine.  However, I do like the simplicity of go-cache for getting started.  How about abstracting the cache implementation to an interface which is pushed down from main()? Can provide go-cache as a simple implementation, but it opens the possibility to provide alternative implementations (memcache/groupcache etc)

Happy to do this for you..

PS - I know this is still early-stages, and really appreciate what you're doing with this.  :smile:

**Comment by janekolszak** [comment]
Cache is going to contain three elements:
- validation key
- consent key
- map with information about clients 

All those are going to be really tiny and I don't see any benefit of having a separate cache just for those three elements. 

But, there's a problem with present implementation - a race condition when the go-cache's janitor deletes an element, but hasn't yet fetched newer data. Asking for data from handlers will then return an error.

**If you feel this cache interface is going to help your work, go ahead and implement it together with go-cache simple implementation.** Just let me know what's your decision so I don't touch this code.

**Comment by janekolszak** [comment]
Can I close this?
this?

**Comment by boyvinall** [comment]
Yeah, sure. Let's close for now.
