### ISSUE TITLE
consider using some logging library instead of fmt.Print ?

### ISSUE THREAD

**Issue by boyvinall** [janekolszak/idp#6]
maybe https://github.com/Sirupsen/logrus or https://github.com/spf13/jWalterWeatherman ?

allows easier debug by knowing which file/linenumber it came from, and also changing verbosity levels etc

**Comment by janekolszak** [comment]
**Agreed!** 

I'm not sure the idp library should log at all. **If yes it would be awesome to make it pluggable (pass a logging func in the configuration)**. Some may want to use fluentd, some logrus for logging.

**Comment by faxal** [comment]
I agree with @janekolszak logging inside library doesn't feel right. 

Maybe we should follow this pattern for debug logs ?

http://dave.cheney.net/2014/09/28/using-build-to-switch-between-debug-and-release

**Comment by janekolszak** [comment]
@faxal This is awesome, let's do it this way.

**Comment by faxal** [comment]
Okay I'm taking this.
